services:
  boma:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boma_analytics
    volumes:
      # Mounts your local project directory into the container
      - .:/opt/app
    working_dir: /opt/app
    # Overrides default command to keep container running indefinitely
    command: tail -f /dev/null
    stdin_open: true
    tty: true
